### ISSUE TITLE
np confounders, no subview of DAG available when running fci.py in examples

### ISSUE THREAD

**Issue by smilesun** [marrlab/causalspyne#21]
```
  warnings.warn(f"there are no confounders in the graph {self._dag} \
/home/playtime/anaconda3/lib/python3.9/site-packages/causalspyne/dag_viewer.py:126: UserWarning: no subview of DAG available
  warnings.warn("no subview of DAG available")
Traceback (most recent call last):
  File "/home/playtime/ProblemSetApproximateCausalDiscovery/examples/fci.py", line 5, in <module>
    arr_data, node_names = gen_partially_observed(size_micro_node_dag=3,
  File "/home/playtime/anaconda3/lib/python3.9/site-packages/causalspyne/main.py", line 43, in gen_partially_observed
    str_node2hide = "_".join(map(str, subview._list_nodes2hide))
TypeError: 'NoneType' object is not iterable

```

**Comment by smilesun** [comment]
```
   raise RuntimeError(f"there are {total_num} confounders to hide, less \
RuntimeError: there are 1 confounders to hide, less                            than the length of [0.5, 1.0]
```

**Comment by smilesun** [comment]
```
python examples/fci.py 
/home/playtime/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/playtime/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (
/home/playtime/anaconda3/lib/python3.9/site-packages/causalspyne/dag_gen.py:70: UserWarning: failed to ensure confounder after                               2 trails for [[ 0.          0.        ]
 [-1.43417388 -0.        ]]
  warnings.warn(f"failed to ensure confounder after \
/home/playtime/anaconda3/lib/python3.9/site-packages/causalspyne/dag_gen.py:70: UserWarning: failed to ensure confounder after                               4 trails for [[-0.         -0.76427547  0.          2.25408092]
 [-0.         -0.         -0.         -0.        ]
 [-0.         -0.37693567  0.          0.        ]
 [-0.          1.54462557 -0.          0.        ]]
  warnings.warn(f"failed to ensure confounder after \
nodes to hide ['v1uv0']
Traceback (most recent call last):
  File "/home/playtime/ProblemSetApproximateCausalDiscovery/examples/fci.py", line 5, in <module>
    arr_data, node_names = gen_partially_observed(size_micro_node_dag=3,
ValueError: too many values to unpack (expected 2)

```

**Comment by smilesun** [comment]
see #5
